---
	create_containers: 2
	default_container_name: docker
	default_container_image: ubuntu
	default_container_command: sleep 1d
	https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-18-04-pt