apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aplicacao-noticas-statefulset
spec:
  serviceName: aplicacao-noticas-statefulset
  selector:
    matchLabels:
      name: aplicacao-noticas-pod-statefulset
  template:
    metadata:
      labels:
        name: aplicacao-noticas-pod-statefulset
    spec:  
      containers:
        - name: container-aplicacao-noticas-statefulset
          image: vccf/aplicacao-noticas:v3
          ports:
            - containerPort: 80
          volumeMounts: 
            - name: imagens
              mountPath: /var/www/html/uploads
            - name: sessoes
              mountPath: /tmp
      volumes:
        - name: imagens
          persistentVolumeClaim: 
            claimName: permissao-imagens
        - name: sessoes
          persistentVolumeClaim: 
            claimName: permissao-sessao    