apiVersion: v1
kind: Service
metadata: 
  name: servico-aplicacao-noticia
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      nodePort: 30100
  selector:
    name: aplicacao-notica-pod


