apiVersion: v1
kind: Service
metadata: 
  name: servico-aplicacao-sistema-statefulset
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      nodePort: 30101
  # o nome passado abaixo deve ser o mesmo nome do selector criado no deployment de aplicacao
  selector:
    name: aplicacao-sistema-pod-statefulset